# Generated by Django 2.1.1 on 2019-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0009_auto_20190101_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockkdinfo',
            name='date',
            field=models.DateField(db_column='Date'),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='highest',
            field=models.DecimalField(db_column='Highest', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='lowest',
            field=models.DecimalField(db_column='Lowest', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='rsv',
            field=models.DecimalField(db_column='RSV', decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='stock',
            field=models.CharField(db_column='Stock', max_length=10, null=True),
        ),
    ]
