# Generated by Django 2.1.1 on 2019-01-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0012_remove_stockkdinfo_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockKDInfo',
        ),
    ]
