# Generated by Django 2.0.4 on 2018-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereesdetails',
            name='remark',
            field=models.CharField(default='new added remark', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refereesdetails',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='refereesmain',
            name='actions',
            field=models.CharField(max_length=200),
        ),
    ]
