# Generated by Django 2.0.4 on 2018-04-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
