# Generated by Django 2.1.1 on 2018-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0002_visitor_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='page',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
