# Generated by Django 2.1.1 on 2018-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0003_visitor_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10, null=True)),
                ('period', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('count', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('remark', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
