# Generated by Django 2.1.1 on 2018-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0005_auto_20181014_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('stock', models.CharField(max_length=10, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
