# Generated by Django 2.1.1 on 2018-12-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0006_stockdailyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKDInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock', models.CharField(max_length=10, null=True)),
                ('highest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rsv', models.DecimalField(decimal_places=4, max_digits=5)),
                ('k', models.DecimalField(decimal_places=4, max_digits=5)),
                ('d', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='stockdailyinfo',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stockdailyinfo',
            old_name='date_time',
            new_name='date',
        ),
    ]
