# Generated by Django 2.1.1 on 2018-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0007_auto_20181229_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='page',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
