# Generated by Django 2.1.1 on 2019-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0010_auto_20190101_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockkdinfo',
            name='close',
            field=models.DecimalField(db_column='Close', decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockkdinfo',
            name='high',
            field=models.DecimalField(db_column='High', decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockkdinfo',
            name='low',
            field=models.DecimalField(db_column='Low', decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
