# Generated by Django 2.1.1 on 2019-08-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0012_auto_20190101_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailyinfo',
            name='close',
            field=models.DecimalField(db_column='close', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockdailyinfo',
            name='high',
            field=models.DecimalField(db_column='high', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockdailyinfo',
            name='low',
            field=models.DecimalField(db_column='low', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='close',
            field=models.DecimalField(db_column='close', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='d',
            field=models.DecimalField(db_column='d', decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='high',
            field=models.DecimalField(db_column='high', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='highest',
            field=models.DecimalField(db_column='highest', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='k',
            field=models.DecimalField(db_column='k', decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='low',
            field=models.DecimalField(db_column='low', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='lowest',
            field=models.DecimalField(db_column='lowest', decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockkdinfo',
            name='rsv',
            field=models.DecimalField(db_column='rsv', decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockpricestatistics',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockpricestatistics',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
